module.exports = [ { block: 'b1' },
  { block: 'b1', elem: 'e1' },
  { block: 'b1', modName: 'm1', modVal: 'v1', elem: 'e1' },
  { block: 'b1', modName: 'm1', modVal: true, elem: 'e1' },
  { block: 'b11' },
  { block: 'b11', modName: 'm1', modVal: 'v1' },
  { block: 'b11', modName: 'm1', modVal: true },
  { block: 'b2' },
  { block: 'b2', elem: 'e2' },
  { block: 'b2', modName: 'm2', modVal: 'v2', elem: 'e2' },
  { block: 'b2', modName: 'm2', modVal: true, elem: 'e2' },
  { block: 'b22' },
  { block: 'b22', modName: 'm2', modVal: 'v2' },
  { block: 'b22', modName: 'm2', modVal: true } ];
