packages:
  - 'packages/*'

catalog:
  # runtime
  debug: ^4.4.3
  glob: ^13.0.6
  is-glob: ^4.0.3
  json5: ^2.2.3
  node-eval: ^2.0.0
  graceful-fs: ^4.2.11
  stringify-object: ^6.0.0
  betterc: ^1.3.0
  change-case: ^5.4.4

  # dev
  typescript: ^6.0.3
  '@types/node': ^25.6.2
  tsx: ^4.21.0
  mocha: ^11.7.5
  '@types/mocha': ^10.0.10
  chai: ^6.2.2
  '@types/chai': ^5.2.3
  chai-as-promised: ^8.0.2
  '@types/chai-as-promised': ^8.0.2
  sinon: ^22.0.0
  '@types/sinon': ^21.0.1
  c8: ^11.0.0
  eslint: ^10.3.0
  '@eslint/js': ^10.0.1
  typescript-eslint: ^8.59.2
  globals: ^17.6.0
  benchmark: ^2.1.4
  '@types/is-glob': ^4.0.4
  '@types/lodash.mergewith': ^4.6.9
  '@types/lodash.uniqwith': ^4.5.9
  '@types/common-tags': ^1.8.4

allowBuilds:
  esbuild: true
